---
#This galaxy role is called and required:
#ansible-galaxy install ansible-network.network-engine 

- name: GENERATE INTERFACE REPORT
  hosts: cisco
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW INTERFACES
      ios_command:
        commands:
          - show interfaces
      register: output
      tags: report

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "~/networking-workshop/parsers/show_interfaces.yaml"
        content: "{{ output.stdout[0] }}"
      tags: report

    - name: DISPLAY THE PARSED DATA
      debug:
        var: interface_facts
      tags: report

    - name: GENERATE REPORT FRAGMENTS
      template:
        src: ~/networking-workshop/templates/interface_facts.j2
        dest: ~/networking-workshop/intf_reports/{{inventory_hostname}}_intf_report.md
      tags: report

    - name: GENERATE A CONSOLIDATED REPORT
      assemble:
        src: ../intf_reports/
        dest: ../interfaces_report.md
      delegate_to: localhost
      run_once: yes
      tags: report
