---
#This galaxy role is called and required:
#ansible-galaxy install ansible-network.network-engine 

- name: GENERATE INTERFACE REPORT
  hosts: cisco
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW INTERFACES
      ios_command:
        commands:
          - show interfaces
      register: output
      tags: report

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "../parsers/show_interfaces.yaml"
        content: "{{ output.stdout[0] }}"
      tags: report
